# Generated by Django 3.0.4 on 2020-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kcart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='Product_Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='Publish_Date',
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='', upload_to='Kcart/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_Category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
