# Generated by Django 3.0.4 on 2020-08-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kcart', '0002_auto_20200720_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=70)),
                ('Email', models.CharField(default='', max_length=70)),
                ('Phone', models.CharField(default='', max_length=70)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
