# Generated by Django 3.0.4 on 2020-08-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kcart', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='additional_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
