# Generated by Django 3.0.4 on 2020-08-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kcart', '0005_auto_20200826_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='additional_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
