# Generated by Django 3.0.4 on 2020-08-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kcart', '0006_auto_20200826_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default='a', max_length=1000),
        ),
    ]
