# Generated by Django 3.0.4 on 2020-08-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kcart', '0007_auto_20200826_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address2',
        ),
    ]
