# Generated by Django 3.0.4 on 2020-08-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kcart', '0008_remove_orders_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address1',
            new_name='address',
        ),
    ]
